
CREATE TABLE Assignments
(
    id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_order    varchar(100) NOT NULL,
    sign_control     varchar(100) NOT NULL,
    sign_performance varchar(100) NOT NULL,
    text_order       text         NOT NULL
);

CREATE TABLE People
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname       varchar(100) NOT NULL,
    name          varchar(100) NOT NULL,
    last_name     varchar(100) NOT NULL,
    job_title     varchar(100) NOT NULL,
    assignments_id int          REFERENCES Assignments (id) ON DELETE SET NULL

);
